[project]
name = "foundation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thanh LE", email = "thanhlq@msn.com" }
]
requires-python = ">=3.14"
dependencies = [
    # Messaging & Serialization
    "fastavro>=1.9.0",
    "msgspec==0.21.1",
    # Legacy / for testing only
    "dataclasses-avroschema==0.70.0",
    "python-schema-registry-client==2.6.1",

    # Database
    "fastnanoid==0.4.3",
    "sqlalchemy==2.0.51",
    "advanced-alchemy[cryptography]==1.11.0",
    "typing_extensions==4.15.0",
    "sniffio==1.3.1",
    "multidict==6.7.1",
    "aiosmtplib==5.1.2",
    # advanced-alchemy use this lib for UUIDv7 support
    "uuid-utils==0.16.2",
    "attrs==26.1.0",
    "pydantic==2.13.4",
    "exceptiongroup==1.3.1",
    "rich==15.0.0",
    "dotenv==0.9.9",
    "python-socketio==5.16.2",
    # To check if needed
    # "trio==0.33.0",
    "cachetools==7.1.4",
    "jinja2>=3.1.6",
    "fast-query-parsers>=1.0.3",

    # Resilience
    "tenacity>=9.0.0",

    # 📊 Monitoring & Logging with Opentelemetry
    # see: https://pypi.org/org/opentelemetry/
    # "opentelemetry-distro==0.54b0",
    # "opentelemetry-exporter-otlp==1.33.0",
    # "opentelemetry-instrumentation==0.54b0",
    # "opentelemetry-instrumentation-logging==0.54b0",
    # "opentelemetry-instrumentation-fastapi==0.54b0",
    # "opentelemetry-instrumentation-aiokafka==0.54b0",
    # "importlib-metadata==8.6.1",
    "importlib-metadata==9.0.0",
    "opentelemetry-exporter-otlp==1.42.1",
    "opentelemetry-instrumentation==0.63b1",
    "opentelemetry-distro==0.63b1",
    "opentelemetry-instrumentation-asyncio==0.63b1",
    "opentelemetry-instrumentation-logging==0.63b1",
    "opentelemetry-instrumentation-fastapi==0.63b1",
    "opentelemetry-instrumentation-aiokafka==0.63b1",
    "opentelemetry-instrumentation-sqlalchemy==0.63b1",
    "opentelemetry-instrumentation-redis==0.63b1",
    "opentelemetry-instrumentation-httpx>=0.63b1",
    "opentelemetry-instrumentation-grpc>=0.63b1",
    "opentelemetry-instrumentation-urllib3==0.63b1",
    "opentelemetry-instrumentation-aiohttp-client==0.63b1",
]

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest==9.0.2",
    "pytest-asyncio>=1.3.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --strict-markers"
asyncio_mode = "auto"
