services:
  ews_api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8191:8191"
    volumes:
       - .:/app
       - /app/.venv
    command: sh -c "uv run --package ews_api python -m ews_api.main"
    env_file:
      - .env_docker

networks:
  default:
    name: external-network
    external: true
