"""
Idempotency repository — all database operations for the idempotency pattern.

Design notes
------------
Race safety
    The critical path uses PostgreSQL's
    ``INSERT … ON CONFLICT (idempotency_key) DO NOTHING``. Two workers racing
    on the same key both attempt the insert; exactly one sees ``rowcount == 1``
    (winner) and the other sees ``rowcount == 0`` (duplicate). No
    application-level locking is required.

TTL cleanup
    :meth:`cleanup_expired` deletes in bounded batches to avoid long-held locks
    on large tables. Call it from a low-priority periodic task, never on the
    hot path.

Session ownership
    Like the outbox/DLQ repositories, every method operates on a
    caller-supplied :class:`AsyncSession` so idempotency writes can participate
    in the surrounding business transaction.
"""

from __future__ import annotations

from datetime import timedelta
from typing import Optional

from db.models.resiliant import ProcessedEventTable
from foundation import BaseService
from foundation.utils import now_in_utc
from sqlalchemy import delete, select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from foundation.resiliant.idempotency import IdempotencyConfig


class IdempotencyRepository(BaseService):
    """
    Database operations for the idempotency subsystem.

    Intentionally thin — it only translates between Python objects and SQL.
    Business logic (guard, key construction, metrics) lives in
    :class:`~resiliant.idempotency.idempotency_service.IdempotencyService`.
    """

    def __init__(self, config: IdempotencyConfig) -> None:
        super().__init__()
        self.config = config

    # ------------------------------------------------------------------
    # Hot-path operations
    # ------------------------------------------------------------------

    async def is_processed(
        self,
        session: AsyncSession,
        idempotency_key: str,
    ) -> bool:
        """
        Check whether an idempotency key has already been recorded.

        Performs a lightweight ``SELECT id … LIMIT 1``; only presence matters,
        so the full row is never materialised.
        """
        stmt = (
            select(ProcessedEventTable.id)
            .where(ProcessedEventTable.idempotency_key == idempotency_key)
            .limit(1)
        )
        result = await session.execute(stmt)
        return result.scalar_one_or_none() is not None

    async def mark_processed(
        self,
        session: AsyncSession,
        idempotency_key: str,
        event_id: str,
        event_type: str,
        handler_name: str,
        *,
        saga_id: Optional[str] = None,
        correlation_id: Optional[str] = None,
        tenant_id: Optional[str] = None,
        extra_metadata: Optional[dict] = None,
    ) -> bool:
        """
        Atomically record an idempotency key on successful processing.

        Uses ``INSERT … ON CONFLICT (idempotency_key) DO NOTHING`` so
        concurrent workers racing on the same key are safe without any
        application-level mutex. The surrogate primary key is generated by the
        model (UUIDv7), so it is left unset here.

        The winner is detected via ``RETURNING id`` rather than ``rowcount``:
        the async psycopg driver reports ``rowcount == -1`` for a plain INSERT,
        so it cannot distinguish an insert from a skipped conflict. With
        ``RETURNING``, a real insert yields the new id while a conflict yields
        no row.

        Returns:
            ``True``  — this call inserted the row (we won the race).
            ``False`` — a duplicate key already existed (someone else won).
        """
        stmt = (
            insert(ProcessedEventTable)
            .values(
                idempotency_key=idempotency_key,
                event_id=event_id,
                event_type=event_type,
                handler_name=handler_name,
                saga_id=saga_id,
                correlation_id=correlation_id,
                tenant_id=tenant_id,
                extra_metadata=extra_metadata,
            )
            .on_conflict_do_nothing(index_elements=['idempotency_key'])
            .returning(ProcessedEventTable.id)
        )

        result = await session.execute(stmt)
        return result.scalar_one_or_none() is not None

    # ------------------------------------------------------------------
    # Read helpers (non-critical path)
    # ------------------------------------------------------------------

    async def get_by_key(
        self,
        session: AsyncSession,
        idempotency_key: str,
    ) -> Optional[ProcessedEventTable]:
        """
        Fetch the full row for a key (diagnostics / audit).

        Do not call on the hot path — use :meth:`is_processed` instead.
        """
        stmt = select(ProcessedEventTable).where(
            ProcessedEventTable.idempotency_key == idempotency_key
        )
        result = await session.execute(stmt)
        return result.scalar_one_or_none()

    # ------------------------------------------------------------------
    # Lifecycle / maintenance
    # ------------------------------------------------------------------

    async def cleanup_expired(
        self,
        session: AsyncSession,
        *,
        ttl_days: Optional[int] = None,
        batch_size: Optional[int] = None,
    ) -> int:
        """
        Delete processed-event rows older than the configured TTL.

        Deletes at most ``batch_size`` rows per call to avoid long-running
        locks. For tables with millions of rows, call in a loop until it
        returns 0. Commits the deletion so the freed rows are visible to other
        workers immediately.
        """
        effective_ttl = ttl_days if ttl_days is not None else self.config.ttl_days
        effective_batch = (
            batch_size if batch_size is not None else self.config.cleanup_batch_size
        )

        # ``created_at`` is TIMESTAMP WITHOUT TIME ZONE, so compare against a
        # naive UTC value to keep the predicate unambiguous.
        threshold = (now_in_utc() - timedelta(days=effective_ttl)).replace(
            tzinfo=None
        )

        # Sub-select the oldest expired ids up to the batch limit so the DELETE
        # touches a bounded, index-ordered set rather than scanning the table.
        ids_subquery = (
            select(ProcessedEventTable.id)
            .where(ProcessedEventTable.created_at < threshold)
            .order_by(ProcessedEventTable.created_at.asc())
            .limit(effective_batch)
            .scalar_subquery()
        )

        stmt = delete(ProcessedEventTable).where(
            ProcessedEventTable.id.in_(ids_subquery)
        )

        result = await session.execute(stmt)
        deleted = result.rowcount or 0
        await session.commit()

        if deleted:
            self.logger.debug(
                'idempotency_cleanup_expired: deleted=%s ttl_days=%s threshold=%s',
                deleted,
                effective_ttl,
                threshold.isoformat(),
            )

        return deleted
