"""user props

Revision ID: 82fb230f445e
Revises: 5f44a5414e1e
Create Date: 2026-06-04 09:12:23.318451

"""

import warnings
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '82fb230f445e'
down_revision = '5f44a5414e1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taas_tasks', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
        batch_op.alter_column('position',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True,
               existing_server_default=sa.text("'-1'::integer"))

    with op.batch_alter_table('taas_user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_index(batch_op.f('ix_taas_user_account_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_user_account_username'), ['username'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taas_user_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taas_user_account_username'))
        batch_op.drop_index(batch_op.f('ix_taas_user_account_email'))
        batch_op.drop_column('properties')

    with op.batch_alter_table('taas_tasks', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
        batch_op.alter_column('display_order',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text("'-1'::integer"))

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
