"""init database

Revision ID: 158f61b713ce
Revises: 
Create Date: 2026-06-01 13:57:35.865343

"""

import warnings
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '158f61b713ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sa.String(length=255), nullable=True),
    sa.Column('v0', sa.String(length=255), nullable=True),
    sa.Column('v1', sa.String(length=255), nullable=True),
    sa.Column('v2', sa.String(length=255), nullable=True),
    sa.Column('v3', sa.String(length=255), nullable=True),
    sa.Column('v4', sa.String(length=255), nullable=True),
    sa.Column('v5', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_casbin_rule'))
    )
    op.create_table('role',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name')),
    sa.UniqueConstraint('slug', name='uq_role_slug')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('ix_role_slug_unique', ['slug'], unique=True)

    op.create_table('taas_categories',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content_type', sa.TEXT(), server_default=sa.text("'md'::character"), nullable=True),
    sa.Column('html_text', sa.TEXT(), nullable=True),
    sa.Column('object_id', sa.TEXT(), nullable=True),
    sa.Column('object_type', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.GUID(length=16), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('last_used_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taas_categories.id'], name=op.f('fk_taas_categories_parent_id_taas_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_categories'))
    )
    op.create_table('taas_crm_accounts',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('org_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('code', sa.TEXT(), nullable=True),
    sa.Column('commercial_name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('alias_id', sa.TEXT(), nullable=True),
    sa.Column('display_name', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('account_type', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('privacy', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('email_alt1', sa.TEXT(), nullable=True),
    sa.Column('email_alt2', sa.TEXT(), nullable=True),
    sa.Column('email_alt3', sa.TEXT(), nullable=True),
    sa.Column('phone_office', sa.TEXT(), nullable=True),
    sa.Column('phone_alternate', sa.TEXT(), nullable=True),
    sa.Column('phone_sanitized', sa.TEXT(), nullable=True),
    sa.Column('website', sa.TEXT(), nullable=True),
    sa.Column('ownership', sa.TEXT(), nullable=True),
    sa.Column('sic_code', sa.TEXT(), nullable=True),
    sa.Column('commercial_id', sa.TEXT(), nullable=True),
    sa.Column('account_function', sa.TEXT(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.TEXT(), nullable=True),
    sa.Column('annual_revenue', sa.TEXT(), nullable=True),
    sa.Column('account_rank', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('is_individual', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('starred', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('starred_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('invoice_warn', sa.Boolean(), nullable=True),
    sa.Column('invoice_warn_message', sa.TEXT(), nullable=True),
    sa.Column('sale_warn', sa.Boolean(), nullable=True),
    sa.Column('sale_warn_message', sa.TEXT(), nullable=True),
    sa.Column('debit_limit', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('currency_id', sa.TEXT(), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('campaign_id', sa.TEXT(), nullable=True),
    sa.Column('avatar_url', sa.TEXT(), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('analytics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_time_entries_checked', sa.TIMESTAMP(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_crm_accounts')),
    sa.UniqueConstraint('slug', name='uq_taas_crm_accounts_slug')
    )
    with op.batch_alter_table('taas_crm_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_is_individual'), ['is_individual'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_privacy'), ['privacy'], unique=False)
        batch_op.create_index('ix_taas_crm_accounts_slug_unique', ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_starred'), ['starred'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('taas_payrates',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('is_initial', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('effective_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('payrate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('currency_id', sa.TEXT(), nullable=True),
    sa.Column('site_id', sa.TEXT(), nullable=True),
    sa.Column('work_type_id', sa.TEXT(), nullable=True),
    sa.Column('work_activity_id', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_payrates'))
    )
    op.create_table('taas_payrates_adjustments',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('effective_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('payrate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('currency_id', sa.TEXT(), nullable=True),
    sa.Column('site_id', sa.TEXT(), nullable=True),
    sa.Column('work_type_id', sa.TEXT(), nullable=True),
    sa.Column('work_activity_id', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_payrates_adjustments'))
    )
    op.create_table('taas_projects',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('org_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('code', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content_type', sa.TEXT(), server_default=sa.text("'md'::character"), nullable=True),
    sa.Column('html_text', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('due_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('engagement_type_id', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'New'::character"), nullable=True),
    sa.Column('status_updated_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('status_updated_by', sa.TEXT(), nullable=True),
    sa.Column('auto_archived', sa.Boolean(), nullable=True),
    sa.Column('privacy', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.GUID(length=16), nullable=True),
    sa.Column('program_id', sa.TEXT(), nullable=True),
    sa.Column('team_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('client_id', sa.TEXT(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analytics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checklists', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_activity_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('starred_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('default_view', sa.TEXT(), nullable=True),
    sa.Column('wiki_start_page_id', sa.TEXT(), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('icon_name', sa.TEXT(), nullable=True),
    sa.Column('avatar_url', sa.TEXT(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=15, scale=7), server_default=sa.text('0'), nullable=True),
    sa.Column('budget_currency_id', sa.TEXT(), nullable=True),
    sa.Column('budget_privacy', sa.TEXT(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('spent_hours', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('spent_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_cost_currency', sa.TEXT(), nullable=True),
    sa.Column('estimated_expense', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_expense_currency', sa.TEXT(), nullable=True),
    sa.Column('total_contract_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_contract_value_currency', sa.TEXT(), nullable=True),
    sa.Column('cost_type', sa.TEXT(), nullable=True),
    sa.Column('billing_type', sa.TEXT(), nullable=True),
    sa.Column('billing_rate_type', sa.TEXT(), nullable=True),
    sa.Column('time_and_expense_to_bill', sa.TEXT(), nullable=True),
    sa.Column('invoice_currency_id', sa.TEXT(), nullable=True),
    sa.Column('sms_template_id', sa.TEXT(), nullable=True),
    sa.Column('mail_template_id', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taas_projects.id'], name=op.f('fk_taas_projects_parent_id_taas_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects'))
    )
    with op.batch_alter_table('taas_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_projects_auto_archived'), ['auto_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_privacy'), ['privacy'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_status'), ['status'], unique=False)

    op.create_table('taas_projects_comments',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('comment_text', sa.TEXT(), nullable=True),
    sa.Column('content_type', sa.TEXT(), server_default=sa.text("'md'::character"), nullable=True),
    sa.Column('html_text', sa.TEXT(), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('icon', sa.TEXT(), nullable=True),
    sa.Column('project_id', sa.TEXT(), nullable=True),
    sa.Column('object_id', sa.TEXT(), nullable=True),
    sa.Column('object_type', sa.TEXT(), server_default=sa.text("'project'::character"), nullable=True),
    sa.Column('privacy', sa.TEXT(), server_default=sa.text("'object'::character"), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects_comments'))
    )
    with op.batch_alter_table('taas_projects_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_projects_comments_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_comments_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_comments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_comments_user_id'), ['user_id'], unique=False)
        batch_op.create_index('taas_projects_comments_default_btree_index', ['project_id', 'object_id', 'object_type'], unique=False)

    op.create_table('taas_tags',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('object_id', sa.TEXT(), nullable=True),
    sa.Column('object_type', sa.TEXT(), nullable=True),
    sa.Column('last_used_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_tags'))
    )
    op.create_table('tag',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('slug', name='uq_tag_slug')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index('ix_tag_slug_unique', ['slug'], unique=True)

    op.create_table('team',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team')),
    sa.UniqueConstraint('slug', name='uq_team_slug')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_name'), ['name'], unique=False)
        batch_op.create_index('ix_team_slug_unique', ['slug'], unique=True)

    op.create_table('user_account',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account'))
    )
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_account_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_account_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_account_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_account_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('actor_id', sa.GUID(length=16), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('target_label', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user_account.id'], name=op.f('fk_audit_log_actor_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    comment='Audit trail for system events and admin actions'
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target_type'), ['target_type'], unique=False)

    op.create_table('email_verification_token',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_email_verification_token_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_token')),
    comment='Email verification tokens for user account verification'
    )
    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verification_token_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_token',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_password_reset_token_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_token')),
    comment='Password reset tokens for secure password recovery'
    )
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_token_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_token',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.GUID(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_refresh_token_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    comment='JWT refresh tokens with rotation tracking'
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_token_user_id'), ['user_id'], unique=False)

    op.create_table('taas_checklist_templates',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('template_type', sa.TEXT(), nullable=True),
    sa.Column('scope', sa.TEXT(), server_default=sa.text("'task'::character"), nullable=True),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('is_template', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_checklist_templates_project_id_taas_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_checklist_templates'))
    )
    with op.batch_alter_table('taas_checklist_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_checklist_templates_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_checklist_templates_scope'), ['scope'], unique=False)

    op.create_table('taas_crm_accounts_addresses',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=100), nullable=True),
    sa.Column('address_postal_code', sa.String(length=20), nullable=True),
    sa.Column('address_country_id', sa.String(length=50), nullable=True),
    sa.Column('address_country_name', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('address_type', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.GUID(length=16), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['taas_crm_accounts.id'], name=op.f('fk_taas_crm_accounts_addresses_account_id_taas_crm_accounts'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_crm_accounts_addresses')),
    sa.UniqueConstraint('slug', name='uq_taas_crm_accounts_addresses_slug')
    )
    with op.batch_alter_table('taas_crm_accounts_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_crm_accounts_addresses_address_type'), ['address_type'], unique=False)
        batch_op.create_index('ix_taas_crm_accounts_addresses_slug_unique', ['slug'], unique=True)

    op.create_table('taas_projects_actions',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_name', sa.TEXT(), nullable=True),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('action_text', sa.TEXT(), nullable=True),
    sa.Column('action_color', sa.TEXT(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('action_type', sa.TEXT(), nullable=True),
    sa.Column('action_value', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_projects_actions_project_id_taas_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects_actions'))
    )
    op.create_table('taas_projects_risks',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('risk_source', sa.TEXT(), nullable=True),
    sa.Column('risk_mitigation_plan', sa.TEXT(), nullable=True),
    sa.Column('risk_status', sa.TEXT(), server_default=sa.text("'new'::character"), nullable=True),
    sa.Column('probability', sa.TEXT(), nullable=True),
    sa.Column('impact', sa.TEXT(), nullable=True),
    sa.Column('probability_value', sa.Integer(), nullable=True),
    sa.Column('impact_value', sa.Integer(), nullable=True),
    sa.Column('impact_cost', sa.Integer(), nullable=True),
    sa.Column('impact_schedule', sa.Integer(), nullable=True),
    sa.Column('impact_performance', sa.Integer(), nullable=True),
    sa.Column('risk_result', sa.Integer(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_projects_risks_project_id_taas_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects_risks'))
    )
    op.create_table('taas_projects_teams',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.TEXT(), nullable=False),
    sa.Column('team_role', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_projects_teams_project_id_taas_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects_teams'))
    )
    with op.batch_alter_table('taas_projects_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_projects_teams_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_teams_team_id'), ['team_id'], unique=False)

    op.create_table('taas_projects_updates',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content_type', sa.TEXT(), server_default=sa.text("'md'::character"), nullable=True),
    sa.Column('html_text', sa.TEXT(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('email_cc', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_projects_updates_project_id_taas_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects_updates'))
    )
    op.create_table('taas_projects_users',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=True),
    sa.Column('starred_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('is_observing', sa.Boolean(), nullable=True),
    sa.Column('email_notification_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('last_activity_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_projects_users_project_id_taas_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects_users'))
    )
    with op.batch_alter_table('taas_projects_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_projects_users_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_users_user_id'), ['user_id'], unique=False)

    op.create_table('taas_projects_workflows',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content_type', sa.TEXT(), server_default=sa.text("'md'::character"), nullable=True),
    sa.Column('html_text', sa.TEXT(), nullable=True),
    sa.Column('workflow_type', sa.TEXT(), server_default=sa.text("'kanban'::character"), nullable=True),
    sa.Column('scope', sa.TEXT(), server_default=sa.text("'project'::character"), nullable=True),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('team_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('template_id', sa.TEXT(), nullable=True),
    sa.Column('allowed_stage_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_template', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('privacy', sa.TEXT(), server_default=sa.text("'project'::character"), nullable=True),
    sa.Column('allowed_work_item_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_item_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('icon', sa.TEXT(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('sms_template_id', sa.TEXT(), nullable=True),
    sa.Column('mail_template_id', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_projects_workflows_project_id_taas_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects_workflows'))
    )
    with op.batch_alter_table('taas_projects_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_projects_workflows_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_projects_workflows_user_id'), ['user_id'], unique=False)

    op.create_table('taas_tags_mapping',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tag_id', sa.GUID(length=16), nullable=True),
    sa.Column('object_id', sa.TEXT(), nullable=True),
    sa.Column('object_type', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['taas_tags.id'], name=op.f('fk_taas_tags_mapping_tag_id_taas_tags')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_tags_mapping'))
    )
    op.create_table('team_invitation',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('invited_by_id', sa.GUID(length=16), nullable=True),
    sa.Column('invited_by_email', sa.String(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['user_account.id'], name=op.f('fk_team_invitation_invited_by_id_user_account'), ondelete='set null'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_invitation_team_id_team'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_invitation'))
    )
    with op.batch_alter_table('team_invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invitation_email'), ['email'], unique=False)

    op.create_table('team_member',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_member_team_id_team'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_team_member_user_id_user_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_member')),
    sa.UniqueConstraint('user_id', 'team_id', name=op.f('uq_team_member_user_id'))
    )
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_member_role'), ['role'], unique=False)

    op.create_table('team_tag',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_team_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_tag_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'tag_id', name=op.f('pk_team_tag'))
    )
    op.create_table('user_account_oauth',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.EncryptedString(key='your-secret-key-here', backend=FernetBackend, length=None), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.EncryptedString(key='your-secret-key-here', backend=FernetBackend, length=None), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('provider_user_data', sa.JSON(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_account_oauth_user_id_user_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account_oauth')),
    comment='Registered OAUTH2 Accounts for Users'
    )
    with op.batch_alter_table('user_account_oauth', schema=None) as batch_op:
        batch_op.create_index('ix_oauth_provider_oauth_id', ['oauth_name', 'account_id'], unique=False)
        batch_op.create_index('ix_oauth_user_provider', ['user_id', 'oauth_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_account_oauth_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_account_oauth_oauth_name'), ['oauth_name'], unique=False)

    op.create_table('user_account_role',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('role_id', sa.GUID(length=16), nullable=False),
    sa.Column('assigned_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_account_role_role_id_role'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_account_role_user_id_user_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account_role')),
    comment='Links a user to a specific role.'
    )
    op.create_table('taas_checklist_items',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('template_id', sa.GUID(length=16), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text("'-1'::integer"), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['taas_checklist_templates.id'], name=op.f('fk_taas_checklist_items_template_id_taas_checklist_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_checklist_items'))
    )
    op.create_table('taas_projects_workflows_assignments',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=False),
    sa.Column('workflow_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.TEXT(), nullable=True),
    sa.Column('assigned_by', sa.TEXT(), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('effective_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('effective_until', sa.TIMESTAMP(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_projects_workflows_assignments_project_id_taas_projects')),
    sa.ForeignKeyConstraint(['workflow_id'], ['taas_projects_workflows.id'], name=op.f('fk_taas_projects_workflows_assignments_workflow_id_taas_projects_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects_workflows_assignments'))
    )
    op.create_table('taas_projects_workflows_stages',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('stage_type', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::character"), nullable=True),
    sa.Column('workflow_id', sa.GUID(length=16), nullable=True),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('owner_user_id', sa.TEXT(), nullable=True),
    sa.Column('default_assignee_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_assign', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('auto_move_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_next_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_previous_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('require_assignee', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('require_due_date', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('enable_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('notification_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('icon', sa.TEXT(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('sort_by', sa.TEXT(), server_default=sa.text("'manual'::character"), nullable=True),
    sa.Column('sort_order', sa.TEXT(), server_default=sa.text("'asc'::character"), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('assignees_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('sms_template_id', sa.TEXT(), nullable=True),
    sa.Column('mail_template_id', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_projects_workflows_stages_project_id_taas_projects')),
    sa.ForeignKeyConstraint(['workflow_id'], ['taas_projects_workflows.id'], name=op.f('fk_taas_projects_workflows_stages_workflow_id_taas_projects_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects_workflows_stages'))
    )
    op.create_table('taas_tasks',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content_type', sa.TEXT(), server_default=sa.text("'md'::character"), nullable=True),
    sa.Column('html_text', sa.TEXT(), nullable=True),
    sa.Column('code', sa.TEXT(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('requested_user_id', sa.TEXT(), nullable=True),
    sa.Column('workflow_id', sa.GUID(length=16), nullable=True),
    sa.Column('stage_id', sa.GUID(length=16), nullable=True),
    sa.Column('stage_type', sa.TEXT(), nullable=True),
    sa.Column('work_item_type_id', sa.TEXT(), nullable=True),
    sa.Column('work_item_type_name', sa.TEXT(), nullable=True),
    sa.Column('work_item_type', sa.TEXT(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_by', sa.TEXT(), nullable=True),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('milestone_id', sa.TEXT(), nullable=True),
    sa.Column('is_recurrence', sa.Boolean(), nullable=True),
    sa.Column('recurrence_id', sa.TEXT(), nullable=True),
    sa.Column('ancestor_id', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.GUID(length=16), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('estimated_cost_currency', sa.TEXT(), nullable=True),
    sa.Column('sale_order_id', sa.TEXT(), nullable=True),
    sa.Column('client_id', sa.TEXT(), nullable=True),
    sa.Column('contact_id', sa.TEXT(), nullable=True),
    sa.Column('privacy', sa.TEXT(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checklists', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assignees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('followers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analytics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('due_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('starred_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('display_order', sa.Float(precision=6), server_default=sa.text('-1'), nullable=True),
    sa.Column('position', sa.Float(precision=6), server_default=sa.text('-1'), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('icon_name', sa.TEXT(), nullable=True),
    sa.Column('time_expense_type', sa.TEXT(), nullable=True),
    sa.Column('timelog_enabled', sa.Boolean(), nullable=True),
    sa.Column('cost_type', sa.TEXT(), nullable=True),
    sa.Column('sms_template_id', sa.TEXT(), nullable=True),
    sa.Column('mail_template_id', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taas_tasks.id'], name=op.f('fk_taas_tasks_parent_id_taas_tasks')),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_tasks_project_id_taas_projects')),
    sa.ForeignKeyConstraint(['stage_id'], ['taas_projects_workflows_stages.id'], name=op.f('fk_taas_tasks_stage_id_taas_projects_workflows_stages')),
    sa.ForeignKeyConstraint(['workflow_id'], ['taas_projects_workflows.id'], name=op.f('fk_taas_tasks_workflow_id_taas_projects_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_tasks'))
    )
    with op.batch_alter_table('taas_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_tasks_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_is_recurrence'), ['is_recurrence'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_privacy'), ['privacy'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_requested_user_id'), ['requested_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_sequence_id'), ['sequence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_stage_type'), ['stage_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_tasks_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('taas_projects_workflows_stages_items',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workflow_id', sa.GUID(length=16), nullable=True),
    sa.Column('stage_id', sa.GUID(length=16), nullable=True),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('task_id', sa.GUID(length=16), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text("'-1'::integer"), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived_by', sa.TEXT(), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_projects_workflows_stages_items_project_id_taas_projects')),
    sa.ForeignKeyConstraint(['stage_id'], ['taas_projects_workflows_stages.id'], name=op.f('fk_taas_projects_workflows_stages_items_stage_id_taas_projects_workflows_stages')),
    sa.ForeignKeyConstraint(['task_id'], ['taas_tasks.id'], name=op.f('fk_taas_projects_workflows_stages_items_task_id_taas_tasks')),
    sa.ForeignKeyConstraint(['workflow_id'], ['taas_projects_workflows.id'], name=op.f('fk_taas_projects_workflows_stages_items_workflow_id_taas_projects_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_projects_workflows_stages_items'))
    )
    op.create_table('taas_task_checklist_items',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('task_id', sa.GUID(length=16), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_by', sa.TEXT(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text("'-1'::integer"), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['taas_tasks.id'], name=op.f('fk_taas_task_checklist_items_task_id_taas_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_task_checklist_items'))
    )
    op.create_table('taas_tasks_users',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_name', sa.TEXT(), nullable=True),
    sa.Column('task_id', sa.GUID(length=16), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['taas_tasks.id'], name=op.f('fk_taas_tasks_users_task_id_taas_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_tasks_users'))
    )
    op.create_table('taas_timelogs',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('task_id', sa.GUID(length=16), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('log_minutes', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('log_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('period_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('period_to', sa.TIMESTAMP(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('timelog_type', sa.TEXT(), server_default=sa.text("'Regular'"), nullable=True),
    sa.Column('is_billable', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_billed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('pay_status', sa.TEXT(), server_default=sa.text("'NA'"), nullable=True),
    sa.Column('invoice_number', sa.TEXT(), nullable=True),
    sa.Column('billing_invoice_id', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Draft'"), nullable=True),
    sa.Column('approved_user_id', sa.TEXT(), nullable=True),
    sa.Column('approved_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('approved_notes', sa.TEXT(), nullable=True),
    sa.Column('is_recording', sa.Boolean(), nullable=True),
    sa.Column('location_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_timelogs_project_id_taas_projects')),
    sa.ForeignKeyConstraint(['task_id'], ['taas_tasks.id'], name=op.f('fk_taas_timelogs_task_id_taas_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_timelogs'))
    )
    op.create_table('taas_payrolls',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('user_code', sa.TEXT(), nullable=True),
    sa.Column('timelog_id', sa.GUID(length=16), nullable=True),
    sa.Column('timelog_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('period_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('period_to', sa.TIMESTAMP(), nullable=True),
    sa.Column('pay_status', sa.TEXT(), server_default=sa.text("'NA'::character"), nullable=True),
    sa.Column('paycode_id', sa.TEXT(), nullable=True),
    sa.Column('paycode_rate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('payrate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('total_log_minutes', sa.Integer(), nullable=True),
    sa.Column('total_log_hours', sa.Integer(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('currency_id', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['timelog_id'], ['taas_timelogs.id'], name=op.f('fk_taas_payrolls_timelog_id_taas_timelogs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_payrolls'))
    )
    op.create_table('taas_payruns',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('payroll_id', sa.GUID(length=16), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('timelog_id', sa.GUID(length=16), nullable=True),
    sa.Column('timelog_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('period_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('period_to', sa.TIMESTAMP(), nullable=True),
    sa.Column('pay_status', sa.TEXT(), nullable=True),
    sa.Column('paycode_id', sa.TEXT(), nullable=True),
    sa.Column('paycode_rate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('payrate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('total_log_minutes', sa.Integer(), nullable=True),
    sa.Column('total_log_hours', sa.Integer(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('currency_id', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payroll_id'], ['taas_payrolls.id'], name=op.f('fk_taas_payruns_payroll_id_taas_payrolls')),
    sa.ForeignKeyConstraint(['timelog_id'], ['taas_timelogs.id'], name=op.f('fk_taas_payruns_timelog_id_taas_timelogs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_payruns'))
    )
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taas_payruns')
    op.drop_table('taas_payrolls')
    op.drop_table('taas_timelogs')
    op.drop_table('taas_tasks_users')
    op.drop_table('taas_task_checklist_items')
    op.drop_table('taas_projects_workflows_stages_items')
    with op.batch_alter_table('taas_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taas_tasks_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_start_date'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_stage_type'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_stage_id'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_sequence_id'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_requested_user_id'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_privacy'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_parent_id'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_name'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_is_recurrence'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_completed_at'))
        batch_op.drop_index(batch_op.f('ix_taas_tasks_code'))

    op.drop_table('taas_tasks')
    op.drop_table('taas_projects_workflows_stages')
    op.drop_table('taas_projects_workflows_assignments')
    op.drop_table('taas_checklist_items')
    op.drop_table('user_account_role')
    with op.batch_alter_table('user_account_oauth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_oauth_oauth_name'))
        batch_op.drop_index(batch_op.f('ix_user_account_oauth_account_id'))
        batch_op.drop_index('ix_oauth_user_provider')
        batch_op.drop_index('ix_oauth_provider_oauth_id')

    op.drop_table('user_account_oauth')
    op.drop_table('team_tag')
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_role'))

    op.drop_table('team_member')
    with op.batch_alter_table('team_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invitation_email'))

    op.drop_table('team_invitation')
    op.drop_table('taas_tags_mapping')
    with op.batch_alter_table('taas_projects_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taas_projects_workflows_user_id'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_workflows_project_id'))

    op.drop_table('taas_projects_workflows')
    with op.batch_alter_table('taas_projects_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taas_projects_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_users_project_id'))

    op.drop_table('taas_projects_users')
    op.drop_table('taas_projects_updates')
    with op.batch_alter_table('taas_projects_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taas_projects_teams_team_id'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_teams_project_id'))

    op.drop_table('taas_projects_teams')
    op.drop_table('taas_projects_risks')
    op.drop_table('taas_projects_actions')
    with op.batch_alter_table('taas_crm_accounts_addresses', schema=None) as batch_op:
        batch_op.drop_index('ix_taas_crm_accounts_addresses_slug_unique')
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_addresses_address_type'))

    op.drop_table('taas_crm_accounts_addresses')
    with op.batch_alter_table('taas_checklist_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taas_checklist_templates_scope'))
        batch_op.drop_index(batch_op.f('ix_taas_checklist_templates_project_id'))

    op.drop_table('taas_checklist_templates')
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_family_id'))

    op.drop_table('refresh_token')
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_token_hash'))

    op.drop_table('password_reset_token')
    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_token_token_hash'))

    op.drop_table('email_verification_token')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_username'))
        batch_op.drop_index(batch_op.f('ix_user_account_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_user_account_status'))
        batch_op.drop_index(batch_op.f('ix_user_account_org_id'))
        batch_op.drop_index(batch_op.f('ix_user_account_email'))

    op.drop_table('user_account')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index('ix_team_slug_unique')
        batch_op.drop_index(batch_op.f('ix_team_name'))

    op.drop_table('team')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index('ix_tag_slug_unique')

    op.drop_table('tag')
    op.drop_table('taas_tags')
    with op.batch_alter_table('taas_projects_comments', schema=None) as batch_op:
        batch_op.drop_index('taas_projects_comments_default_btree_index')
        batch_op.drop_index(batch_op.f('ix_taas_projects_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_comments_project_id'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_comments_object_type'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_comments_object_id'))

    op.drop_table('taas_projects_comments')
    with op.batch_alter_table('taas_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taas_projects_status'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_start_date'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_privacy'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_org_id'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_name'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_due_date'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_code'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_client_id'))
        batch_op.drop_index(batch_op.f('ix_taas_projects_auto_archived'))

    op.drop_table('taas_projects')
    op.drop_table('taas_payrates_adjustments')
    op.drop_table('taas_payrates')
    with op.batch_alter_table('taas_crm_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_status'))
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_starred'))
        batch_op.drop_index('ix_taas_crm_accounts_slug_unique')
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_privacy'))
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_parent_id'))
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_org_id'))
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_is_individual'))
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_email'))
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_code'))
        batch_op.drop_index(batch_op.f('ix_taas_crm_accounts_account_type'))

    op.drop_table('taas_crm_accounts')
    op.drop_table('taas_categories')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('ix_role_slug_unique')

    op.drop_table('role')
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
