"""ppm v2 health

Revision ID: 106f9b722e00
Revises: 8e88de5c0d0e
Create Date: 2026-10-10 03:22:48.590791

"""

import warnings
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
import sqlalchemy.dialects.postgresql.named_types as pg_types    # <--- Add this line.
from alembic import op
from db.migrations.utils import check_enum_exists    # <--- Add this line.
from db.models.types import JSONText              # <--- Add this line.
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '106f9b722e00'
down_revision = '8e88de5c0d0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taas_ppm_health_overrides',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.Column('set_by', sa.String(length=320), nullable=False),
    sa.Column('cleared_by', sa.String(length=320), nullable=True),
    sa.Column('cleared_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=8), server_default=sa.text("'active'"), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("rating in ('green', 'amber', 'red')", name=op.f('ck_taas_ppm_health_overrides_rating')),
    sa.CheckConstraint("status in ('active', 'expired', 'cleared')", name=op.f('ck_taas_ppm_health_overrides_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_ppm_health_overrides_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_ppm_health_overrides_project_id_taas_projects'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_health_overrides_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_health_overrides'))
    )
    with op.batch_alter_table('taas_ppm_health_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_ppm_health_overrides_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_health_overrides_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_ppm_health_overrides_active', ['project_id'], unique=True, postgresql_where=sa.text("status = 'active'"))

    op.create_table('taas_ppm_health_policies',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_ppm_health_policies_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_ppm_health_policies_project_id_taas_projects'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_health_policies_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_health_policies'))
    )
    with op.batch_alter_table('taas_ppm_health_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_ppm_health_policies_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_ppm_health_policies_org', ['organization_id'], unique=True, postgresql_where=sa.text('project_id is null'))
        batch_op.create_index('ux_taas_ppm_health_policies_project', ['project_id'], unique=True)

    op.create_table('taas_ppm_health_snapshots',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('schedule', sa.String(length=8), server_default=sa.text("'none'"), nullable=False),
    sa.Column('budget', sa.String(length=8), server_default=sa.text("'none'"), nullable=False),
    sa.Column('resources', sa.String(length=8), server_default=sa.text("'none'"), nullable=False),
    sa.Column('scope', sa.String(length=8), server_default=sa.text("'none'"), nullable=False),
    sa.Column('quality', sa.String(length=8), server_default=sa.text("'none'"), nullable=False),
    sa.Column('risk', sa.String(length=8), server_default=sa.text("'none'"), nullable=False),
    sa.Column('overall', sa.String(length=8), server_default=sa.text("'none'"), nullable=False),
    sa.Column('overall_effective', sa.String(length=8), server_default=sa.text("'none'"), nullable=False),
    sa.Column('override_id', sa.GUID(length=16), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("budget in ('green', 'amber', 'red', 'none')", name=op.f('ck_taas_ppm_health_snapshots_budget')),
    sa.CheckConstraint("overall in ('green', 'amber', 'red', 'none')", name=op.f('ck_taas_ppm_health_snapshots_overall')),
    sa.CheckConstraint("overall_effective in ('green', 'amber', 'red', 'none')", name=op.f('ck_taas_ppm_health_snapshots_overall_effective')),
    sa.CheckConstraint("quality in ('green', 'amber', 'red', 'none')", name=op.f('ck_taas_ppm_health_snapshots_quality')),
    sa.CheckConstraint("resources in ('green', 'amber', 'red', 'none')", name=op.f('ck_taas_ppm_health_snapshots_resources')),
    sa.CheckConstraint("risk in ('green', 'amber', 'red', 'none')", name=op.f('ck_taas_ppm_health_snapshots_risk')),
    sa.CheckConstraint("schedule in ('green', 'amber', 'red', 'none')", name=op.f('ck_taas_ppm_health_snapshots_schedule')),
    sa.CheckConstraint("scope in ('green', 'amber', 'red', 'none')", name=op.f('ck_taas_ppm_health_snapshots_scope')),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_ppm_health_snapshots_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_ppm_health_snapshots_project_id_taas_projects'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_health_snapshots_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_health_snapshots'))
    )
    with op.batch_alter_table('taas_ppm_health_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_taas_ppm_health_snapshots_date', ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_health_snapshots_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_health_snapshots_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_ppm_health_snapshots_day', ['project_id', 'snapshot_date'], unique=True)
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    for table, indexes in (
        ('taas_ppm_health_snapshots', ('ux_taas_ppm_health_snapshots_day', 'ix_taas_ppm_health_snapshots_tenant_id', 'ix_taas_ppm_health_snapshots_organization_id', 'ix_taas_ppm_health_snapshots_date')),
        ('taas_ppm_health_policies', ('ux_taas_ppm_health_policies_project', 'ux_taas_ppm_health_policies_org', 'ix_taas_ppm_health_policies_tenant_id')),
        ('taas_ppm_health_overrides', ('ux_taas_ppm_health_overrides_active', 'ix_taas_ppm_health_overrides_tenant_id', 'ix_taas_ppm_health_overrides_organization_id')),
    ):
        with op.batch_alter_table(table, schema=None) as batch_op:
            for index in indexes:
                batch_op.drop_index(index)
        op.drop_table(table)


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
