"""ppm v2 dashboards

Revision ID: 339ae1dc6f78
Revises: 106f9b722e00
Create Date: 2026-10-10 04:02:14.220041

"""

import warnings
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
import sqlalchemy.dialects.postgresql.named_types as pg_types    # <--- Add this line.
from alembic import op
from db.migrations.utils import check_enum_exists    # <--- Add this line.
from db.models.types import JSONText              # <--- Add this line.
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '339ae1dc6f78'
down_revision = '106f9b722e00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taas_ppm_dashboards',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('scope_type', sa.String(length=16), server_default=sa.text("'personal'"), nullable=False),
    sa.Column('scope_id', sa.GUID(length=16), nullable=True),
    sa.Column('owner', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default=sa.text("'private'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("scope_type in ('personal', 'project', 'organization')", name=op.f('ck_taas_ppm_dashboards_scope_type')),
    sa.CheckConstraint("visibility in ('private', 'shared', 'scope')", name=op.f('ck_taas_ppm_dashboards_visibility')),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_ppm_dashboards_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_dashboards_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_dashboards'))
    )
    with op.batch_alter_table('taas_ppm_dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_ppm_dashboards_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_taas_ppm_dashboards_scope', ['organization_id', 'scope_type', 'scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_dashboards_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_ppm_project_daily_stats',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=False),
    sa.Column('iteration_id', sa.GUID(length=16), nullable=True),
    sa.Column('stats_date', sa.Date(), nullable=False),
    sa.Column('items_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_done', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_open', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_overdue', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_added', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('estimate_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('remaining_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('logged_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('billable_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['taas_projects_iterations.id'], name=op.f('fk_taas_ppm_project_daily_stats_iteration_id_taas_projects_iterations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_ppm_project_daily_stats_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_ppm_project_daily_stats_project_id_taas_projects'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_project_daily_stats_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_project_daily_stats'))
    )
    with op.batch_alter_table('taas_ppm_project_daily_stats', schema=None) as batch_op:
        batch_op.create_index('ix_taas_ppm_project_daily_stats_date', ['stats_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_project_daily_stats_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_project_daily_stats_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_ppm_project_daily_stats_iteration', ['iteration_id', 'stats_date'], unique=True, postgresql_where=sa.text('iteration_id is not null'))
        batch_op.create_index('ux_taas_ppm_project_daily_stats_project', ['project_id', 'stats_date'], unique=True, postgresql_where=sa.text('iteration_id is null'))

    op.create_table('taas_ppm_dashboard_shares',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('dashboard_id', sa.GUID(length=16), nullable=False),
    sa.Column('principal_type', sa.String(length=8), server_default=sa.text("'user'"), nullable=False),
    sa.Column('principal_id', sa.String(length=320), nullable=False),
    sa.Column('can_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("principal_type in ('user', 'role')", name=op.f('ck_taas_ppm_dashboard_shares_principal_type')),
    sa.ForeignKeyConstraint(['dashboard_id'], ['taas_ppm_dashboards.id'], name=op.f('fk_taas_ppm_dashboard_shares_dashboard_id_taas_ppm_dashboards'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_dashboard_shares_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_dashboard_shares'))
    )
    with op.batch_alter_table('taas_ppm_dashboard_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_ppm_dashboard_shares_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_ppm_dashboard_shares_principal', ['dashboard_id', 'principal_type', 'principal_id'], unique=True)
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    for table, indexes in (
        ('taas_ppm_dashboard_shares', ('ux_taas_ppm_dashboard_shares_principal', 'ix_taas_ppm_dashboard_shares_tenant_id')),
        ('taas_ppm_project_daily_stats', ('ux_taas_ppm_project_daily_stats_project', 'ux_taas_ppm_project_daily_stats_iteration', 'ix_taas_ppm_project_daily_stats_tenant_id', 'ix_taas_ppm_project_daily_stats_organization_id', 'ix_taas_ppm_project_daily_stats_date')),
        ('taas_ppm_dashboards', ('ix_taas_ppm_dashboards_tenant_id', 'ix_taas_ppm_dashboards_scope', 'ix_taas_ppm_dashboards_organization_id')),
    ):
        with op.batch_alter_table(table, schema=None) as batch_op:
            for index in indexes:
                batch_op.drop_index(index)
        op.drop_table(table)


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
