"""ppm v2 automation

Revision ID: 3b4e530684c4
Revises: 339ae1dc6f78
Create Date: 2026-10-10 04:39:33.557032

"""

import warnings
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
import sqlalchemy.dialects.postgresql.named_types as pg_types    # <--- Add this line.
from alembic import op
from db.migrations.utils import check_enum_exists    # <--- Add this line.
from db.models.types import JSONText              # <--- Add this line.
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '3b4e530684c4'
down_revision = '339ae1dc6f78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taas_ppm_automation_rules',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('scope_type', sa.String(length=16), server_default=sa.text("'project'"), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('item_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'disabled'"), nullable=False),
    sa.Column('owner', sa.String(length=320), nullable=False),
    sa.Column('owner_user_id', sa.GUID(length=16), nullable=True),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('trigger_event', sa.String(length=80), nullable=True),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=True),
    sa.Column('position', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("scope_type in ('project', 'organization')", name=op.f('ck_taas_ppm_automation_rules_scope_type')),
    sa.CheckConstraint("status in ('active', 'paused', 'disabled')", name=op.f('ck_taas_ppm_automation_rules_status')),
    sa.CheckConstraint("trigger_type in ('event', 'relative', 'schedule')", name=op.f('ck_taas_ppm_automation_rules_trigger_type')),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_ppm_automation_rules_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_ppm_automation_rules_project_id_taas_projects'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_automation_rules_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_automation_rules'))
    )
    with op.batch_alter_table('taas_ppm_automation_rules', schema=None) as batch_op:
        batch_op.create_index('ix_taas_ppm_automation_rules_due', ['next_run_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
        batch_op.create_index('ix_taas_ppm_automation_rules_event', ['organization_id', 'trigger_event', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_automation_rules_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_automation_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_ppm_automation_runs',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('rule_id', sa.GUID(length=16), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('occurrence_key', sa.String(length=200), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('depth', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('mode', sa.String(length=8), server_default=sa.text("'live'"), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('undone_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('undone_by', sa.String(length=320), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("mode in ('live', 'test')", name=op.f('ck_taas_ppm_automation_runs_mode')),
    sa.CheckConstraint("status in ('succeeded', 'skipped', 'failed', 'throttled', 'loop_blocked', 'dry_run', 'undone')", name=op.f('ck_taas_ppm_automation_runs_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_ppm_automation_runs_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['rule_id'], ['taas_ppm_automation_rules.id'], name=op.f('fk_taas_ppm_automation_runs_rule_id_taas_ppm_automation_rules'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_automation_runs_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_automation_runs'))
    )
    with op.batch_alter_table('taas_ppm_automation_runs', schema=None) as batch_op:
        batch_op.create_index('ix_taas_ppm_automation_runs_rule', ['rule_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index('ix_taas_ppm_automation_runs_subject', ['subject_type', 'subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_automation_runs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_ppm_automation_runs_occurrence', ['rule_id', 'occurrence_key'], unique=True, postgresql_where=sa.text("mode = 'live'"))
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    for table, indexes in (
        ('taas_ppm_automation_runs', ('ux_taas_ppm_automation_runs_occurrence', 'ix_taas_ppm_automation_runs_rule', 'ix_taas_ppm_automation_runs_subject', 'ix_taas_ppm_automation_runs_tenant_id')),
        ('taas_ppm_automation_rules', ('ix_taas_ppm_automation_rules_event', 'ix_taas_ppm_automation_rules_due', 'ix_taas_ppm_automation_rules_tenant_id', 'ix_taas_ppm_automation_rules_project_id')),
    ):
        with op.batch_alter_table(table, schema=None) as batch_op:
            for index in indexes:
                batch_op.drop_index(index)
        op.drop_table(table)


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
