"""sites and media: taas_site_* (site builder) and taas_media_* (media library)

Specs: taas-specs/site-builder/, taas-specs/media/.

Revision ID: f52cd8075cbe
Revises: c4a7e2f19d30
Create Date: 2026-10-05 23:29:52.761075

"""

import warnings
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
import sqlalchemy.dialects.postgresql.named_types as pg_types    # <--- Add this line.
from alembic import op
from db.migrations.utils import check_enum_exists    # <--- Add this line.
from db.models.types import JSONText              # <--- Add this line.
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = 'f52cd8075cbe'
down_revision = 'c4a7e2f19d30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taas_site_ai_usage',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.BigInteger(), nullable=False),
    sa.Column('tokens_out', sa.BigInteger(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_site_ai_usage_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_site_ai_usage')),
    sa.UniqueConstraint('tenant_id', 'period', name='uq_taas_site_ai_usage_period')
    )
    with op.batch_alter_table('taas_site_ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_site_ai_usage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_site_audit',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('site_id', sa.GUID(length=16), nullable=True),
    sa.Column('actor_id', sa.GUID(length=16), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_site_audit_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_site_audit'))
    )
    with op.batch_alter_table('taas_site_audit', schema=None) as batch_op:
        batch_op.create_index('ix_taas_site_audit_site', ['site_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_audit_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_media_folders',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('parent_id', sa.GUID(length=16), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_media_folders_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['parent_id'], ['taas_media_folders.id'], name=op.f('fk_taas_media_folders_parent_id_taas_media_folders'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_media_folders_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_media_folders'))
    )
    with op.batch_alter_table('taas_media_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_media_folders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_media_folders_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_media_folders_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_media_folders_name', ['organization_id', sa.literal_column("coalesce(parent_id, '00000000-0000-0000-0000-000000000000'::uuid)"), sa.literal_column('lower(name)')], unique=True)

    op.create_table('taas_site_sites',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('default_locale', sa.String(length=16), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=True),
    sa.Column('home_page_id', sa.GUID(length=16), nullable=True),
    sa.Column('not_found_page_id', sa.GUID(length=16), nullable=True),
    sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('live_release_id', sa.GUID(length=16), nullable=True),
    sa.Column('published_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('preview_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=True),
    sa.Column('archived_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_site_sites_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_site_sites_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_site_sites'))
    )
    with op.batch_alter_table('taas_site_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_site_sites_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_sites_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_sites_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_site_sites_org_root', ['organization_id'], unique=True, postgresql_where=sa.text('is_root AND deleted_at IS NULL'))
        batch_op.create_index('ux_taas_site_sites_org_slug', ['organization_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))

    op.create_table('taas_media_assets',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('folder_id', sa.GUID(length=16), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('ext', sa.String(length=16), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.String(length=2000), nullable=True),
    sa.Column('focal_x', sa.Float(), nullable=False),
    sa.Column('focal_y', sa.Float(), nullable=False),
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variants_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=True),
    sa.Column('updated_by', sa.GUID(length=16), nullable=True),
    sa.Column('deleted_by', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['taas_media_folders.id'], name=op.f('fk_taas_media_assets_folder_id_taas_media_folders'), ondelete='set null'),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_media_assets_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_media_assets_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_media_assets'))
    )
    with op.batch_alter_table('taas_media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_media_assets_checksum'), ['checksum'], unique=False)
        batch_op.create_index('ix_taas_media_assets_org_folder', ['organization_id', 'folder_id'], unique=False)
        batch_op.create_index('ix_taas_media_assets_org_kind', ['organization_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_media_assets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_media_assets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_site_form_submissions',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('site_id', sa.GUID(length=16), nullable=False),
    sa.Column('page_id', sa.GUID(length=16), nullable=True),
    sa.Column('form_key', sa.String(length=64), nullable=False),
    sa.Column('form_title', sa.String(length=200), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['taas_site_sites.id'], name=op.f('fk_taas_site_form_submissions_site_id_taas_site_sites'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_site_form_submissions_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_site_form_submissions'))
    )
    with op.batch_alter_table('taas_site_form_submissions', schema=None) as batch_op:
        batch_op.create_index('ix_taas_site_form_submissions_site', ['site_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_form_submissions_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_form_submissions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_site_menus',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('site_id', sa.GUID(length=16), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['taas_site_sites.id'], name=op.f('fk_taas_site_menus_site_id_taas_site_sites'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_site_menus_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_site_menus')),
    sa.UniqueConstraint('site_id', 'key', name='uq_taas_site_menus_key')
    )
    with op.batch_alter_table('taas_site_menus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_site_menus_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_menus_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_site_pages',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('site_id', sa.GUID(length=16), nullable=False),
    sa.Column('parent_id', sa.GUID(length=16), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('in_menu', sa.Boolean(), nullable=False),
    sa.Column('noindex', sa.Boolean(), nullable=False),
    sa.Column('seo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('draft_revision_id', sa.GUID(length=16), nullable=True),
    sa.Column('published_revision_id', sa.GUID(length=16), nullable=True),
    sa.Column('locked_by', sa.GUID(length=16), nullable=True),
    sa.Column('locked_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('created_by', sa.GUID(length=16), nullable=True),
    sa.Column('updated_by', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['taas_site_pages.id'], name=op.f('fk_taas_site_pages_parent_id_taas_site_pages'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['site_id'], ['taas_site_sites.id'], name=op.f('fk_taas_site_pages_site_id_taas_site_sites'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_site_pages_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_site_pages'))
    )
    with op.batch_alter_table('taas_site_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_site_pages_site_id'), ['site_id'], unique=False)
        batch_op.create_index('ix_taas_site_pages_site_parent', ['site_id', 'parent_id', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_pages_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_site_pages_site_path', ['site_id', 'locale', 'path'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))

    op.create_table('taas_site_redirects',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('site_id', sa.GUID(length=16), nullable=False),
    sa.Column('from_path', sa.String(length=512), nullable=False),
    sa.Column('to', sa.String(length=1024), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['taas_site_sites.id'], name=op.f('fk_taas_site_redirects_site_id_taas_site_sites'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_site_redirects_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_site_redirects')),
    sa.UniqueConstraint('site_id', 'from_path', name='uq_taas_site_redirects_from')
    )
    with op.batch_alter_table('taas_site_redirects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_site_redirects_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_redirects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_site_releases',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('site_id', sa.GUID(length=16), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('published_by', sa.GUID(length=16), nullable=True),
    sa.Column('published_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('rollback_of', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['taas_site_sites.id'], name=op.f('fk_taas_site_releases_site_id_taas_site_sites'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_site_releases_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_site_releases')),
    sa.UniqueConstraint('site_id', 'number', name='uq_taas_site_releases_number')
    )
    with op.batch_alter_table('taas_site_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_site_releases_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_releases_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_media_favorites',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('asset_id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['taas_media_assets.id'], name=op.f('fk_taas_media_favorites_asset_id_taas_media_assets'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_media_favorites_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_media_favorites')),
    sa.UniqueConstraint('user_id', 'asset_id', name='uq_taas_media_favorites_user_asset')
    )
    with op.batch_alter_table('taas_media_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_media_favorites_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_media_favorites_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_media_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('taas_media_usages',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('asset_id', sa.GUID(length=16), nullable=False),
    sa.Column('app', sa.String(length=32), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.GUID(length=16), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('used_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['taas_media_assets.id'], name=op.f('fk_taas_media_usages_asset_id_taas_media_assets'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_media_usages_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_media_usages')),
    sa.UniqueConstraint('asset_id', 'app', 'ref_type', 'ref_id', name='uq_taas_media_usages_ref')
    )
    with op.batch_alter_table('taas_media_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_media_usages_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index('ix_taas_media_usages_ref', ['app', 'ref_type', 'ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_media_usages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_site_page_revisions',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('site_id', sa.GUID(length=16), nullable=False),
    sa.Column('page_id', sa.GUID(length=16), nullable=False),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('seo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author_id', sa.GUID(length=16), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['taas_site_pages.id'], name=op.f('fk_taas_site_page_revisions_page_id_taas_site_pages'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['site_id'], ['taas_site_sites.id'], name=op.f('fk_taas_site_page_revisions_site_id_taas_site_sites'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_site_page_revisions_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_site_page_revisions'))
    )
    with op.batch_alter_table('taas_site_page_revisions', schema=None) as batch_op:
        batch_op.create_index('ix_taas_site_page_revisions_page', ['page_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_page_revisions_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_site_page_revisions_tenant_id'), ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    op.drop_table('taas_site_page_revisions')
    op.drop_table('taas_media_usages')
    op.drop_table('taas_media_favorites')
    op.drop_table('taas_site_releases')
    op.drop_table('taas_site_redirects')
    op.drop_table('taas_site_pages')
    op.drop_table('taas_site_menus')
    op.drop_table('taas_site_form_submissions')
    op.drop_table('taas_media_assets')
    op.drop_table('taas_site_sites')
    op.drop_table('taas_media_folders')
    op.drop_table('taas_site_audit')
    op.drop_table('taas_site_ai_usage')


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
