"""ppm v2 intake

Revision ID: 67ade2acd43b
Revises: 3b4e530684c4
Create Date: 2026-10-10 04:53:47.645575

"""

import warnings
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
import sqlalchemy.dialects.postgresql.named_types as pg_types    # <--- Add this line.
from alembic import op
from db.migrations.utils import check_enum_exists    # <--- Add this line.
from db.models.types import JSONText              # <--- Add this line.
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '67ade2acd43b'
down_revision = '3b4e530684c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taas_ppm_forms',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audience', sa.String(length=16), server_default=sa.text("'internal'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('current_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=True),
    sa.Column('queue_project_id', sa.GUID(length=16), nullable=True),
    sa.Column('request_type_key', sa.String(length=64), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner', sa.String(length=320), nullable=False),
    sa.Column('owner_user_id', sa.GUID(length=16), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("audience in ('internal', 'public')", name=op.f('ck_taas_ppm_forms_audience')),
    sa.CheckConstraint("status in ('draft', 'published', 'closed')", name=op.f('ck_taas_ppm_forms_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_ppm_forms_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_ppm_forms_project_id_taas_projects'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['queue_project_id'], ['taas_projects.id'], name=op.f('fk_taas_ppm_forms_queue_project_id_taas_projects'), ondelete='set null'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_forms_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_forms'))
    )
    with op.batch_alter_table('taas_ppm_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_ppm_forms_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_forms_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_ppm_forms_public_id', ['public_id'], unique=True, postgresql_where=sa.text('public_id is not null'))

    op.create_table('taas_ppm_form_versions',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('form_id', sa.GUID(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_by', sa.String(length=320), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['taas_ppm_forms.id'], name=op.f('fk_taas_ppm_form_versions_form_id_taas_ppm_forms'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_form_versions_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_form_versions'))
    )
    with op.batch_alter_table('taas_ppm_form_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_ppm_form_versions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_ppm_form_versions_version', ['form_id', 'version'], unique=True)

    op.create_table('taas_ppm_requests',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('task_id', sa.GUID(length=16), nullable=False),
    sa.Column('form_id', sa.GUID(length=16), nullable=False),
    sa.Column('form_version', sa.Integer(), nullable=False),
    sa.Column('requester_ref', sa.String(length=320), nullable=True),
    sa.Column('requester_name', sa.String(length=200), nullable=True),
    sa.Column('requester_email', sa.String(length=320), nullable=True),
    sa.Column('is_member', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('requester_locale', sa.String(length=16), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'submitted'"), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=320), nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('result_project_id', sa.GUID(length=16), nullable=True),
    sa.Column('result_task_id', sa.GUID(length=16), nullable=True),
    sa.Column('duplicate_of', sa.GUID(length=16), nullable=True),
    sa.Column('routing_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tracking_hash', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('submitted', 'in_review', 'needs_info', 'accepted', 'in_progress', 'done', 'rejected', 'duplicate', 'withdrawn', 'cancelled')", name=op.f('ck_taas_ppm_requests_status')),
    sa.ForeignKeyConstraint(['form_id'], ['taas_ppm_forms.id'], name=op.f('fk_taas_ppm_requests_form_id_taas_ppm_forms'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_ppm_requests_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['task_id'], ['taas_tasks.id'], name=op.f('fk_taas_ppm_requests_task_id_taas_tasks'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_requests_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_requests'))
    )
    with op.batch_alter_table('taas_ppm_requests', schema=None) as batch_op:
        batch_op.create_index('ix_taas_ppm_requests_form', ['form_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_taas_ppm_requests_requester', ['organization_id', 'requester_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_requests_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_ppm_requests_idempotency', ['form_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key is not null'))
        batch_op.create_index('ux_taas_ppm_requests_task', ['task_id'], unique=True)
        batch_op.create_index('ux_taas_ppm_requests_tracking', ['tracking_hash'], unique=True, postgresql_where=sa.text('tracking_hash is not null'))
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    for table, indexes in (
        ('taas_ppm_requests', ('ux_taas_ppm_requests_tracking', 'ux_taas_ppm_requests_task', 'ux_taas_ppm_requests_idempotency', 'ix_taas_ppm_requests_tenant_id', 'ix_taas_ppm_requests_requester', 'ix_taas_ppm_requests_organization_id', 'ix_taas_ppm_requests_form')),
        ('taas_ppm_form_versions', None),
        ('taas_ppm_forms', None),
    ):
        if indexes:
            with op.batch_alter_table(table, schema=None) as batch_op:
                for index in indexes:
                    batch_op.drop_index(index)
        op.drop_table(table)


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
