"""crm contacts

Revision ID: 02f24a9e6949
Revises: 67ade2acd43b
Create Date: 2026-10-10 07:17:49.389642

"""

import warnings
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
import sqlalchemy.dialects.postgresql.named_types as pg_types    # <--- Add this line.
from alembic import op
from db.migrations.utils import check_enum_exists    # <--- Add this line.
from db.models.types import JSONText              # <--- Add this line.
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '02f24a9e6949'
down_revision = '67ade2acd43b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taas_crm_contacts',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('organization_id', sa.GUID(length=16), nullable=False),
    sa.Column('account_id', sa.GUID(length=16), nullable=True),
    sa.Column('salutation', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('emails', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('phones', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('owner', sa.String(length=320), nullable=True),
    sa.Column('lead_source', sa.String(length=40), nullable=True),
    sa.Column('reports_to_id', sa.GUID(length=16), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.String(length=320), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['taas_crm_accounts.id'], name=op.f('fk_taas_crm_contacts_account_id_taas_crm_accounts'), ondelete='set null'),
    sa.ForeignKeyConstraint(['organization_id'], ['taas_organizations.id'], name=op.f('fk_taas_crm_contacts_organization_id_taas_organizations'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['reports_to_id'], ['taas_crm_contacts.id'], name=op.f('fk_taas_crm_contacts_reports_to_id_taas_crm_contacts'), ondelete='set null'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_crm_contacts_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_crm_contacts'))
    )
    with op.batch_alter_table('taas_crm_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_crm_contacts_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_taas_crm_contacts_email', ['organization_id', 'email'], unique=False)
        batch_op.create_index('ix_taas_crm_contacts_name', ['organization_id', 'name'], unique=False)
        batch_op.create_index('ix_taas_crm_contacts_scope', ['organization_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_crm_contacts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taas_ppm_project_contacts',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('tenant_id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=False),
    sa.Column('contact_id', sa.GUID(length=16), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['taas_crm_contacts.id'], name=op.f('fk_taas_ppm_project_contacts_contact_id_taas_crm_contacts'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['project_id'], ['taas_projects.id'], name=op.f('fk_taas_ppm_project_contacts_project_id_taas_projects'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['tenant_id'], ['taas_tenants.id'], name=op.f('fk_taas_ppm_project_contacts_tenant_id_taas_tenants'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taas_ppm_project_contacts'))
    )
    with op.batch_alter_table('taas_ppm_project_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taas_ppm_project_contacts_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taas_ppm_project_contacts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_taas_ppm_project_contacts_default', ['project_id'], unique=True, postgresql_where=sa.text('is_default'))
        batch_op.create_index('ux_taas_ppm_project_contacts_pair', ['project_id', 'contact_id'], unique=True)

    with op.batch_alter_table('taas_crm_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_contact_id', sa.GUID(length=16), nullable=True))
        batch_op.create_foreign_key('fk_taas_crm_accounts_primary_contact_id_taas_crm_contacts', 'taas_crm_contacts', ['primary_contact_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    with op.batch_alter_table('taas_crm_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_taas_crm_accounts_primary_contact_id_taas_crm_contacts', type_='foreignkey')
        batch_op.drop_column('primary_contact_id')
    op.drop_table('taas_ppm_project_contacts')
    op.drop_table('taas_crm_contacts')


def data_upgrades() -> None:
    """Each account's ``account_metadata.primary_contact`` ``{name, email, phone}`` becomes a contact of the account and
    its ``primary_contact_id`` (ADR-10); the metadata stays for a downgrade."""
    import json
    import uuid

    bind = op.get_bind()
    rows = bind.execute(
        sa.text(
            "select id, tenant_id, organization_id, account_metadata -> 'primary_contact' as contact "
            "from taas_crm_accounts where tenant_id is not null and organization_id is not null "
            "and account_metadata ? 'primary_contact'"
        )
    ).mappings()
    for row in list(rows):
        contact = row['contact'] if isinstance(row['contact'], dict) else {}
        name = str(contact.get('name') or '').strip()
        email = str(contact.get('email') or '').strip().lower()
        phone = str(contact.get('phone') or '').strip()
        if not (name or email or phone):
            continue
        first, _, last = name.partition(' ')
        contact_id = uuid.uuid7()
        bind.execute(
            sa.text(
                "insert into taas_crm_contacts (id, tenant_id, organization_id, account_id, first_name, last_name, name, "
                "email, phone, emails, phones, addresses, labels, created_at, updated_at) values (:id, :tenant, :org, "
                ":account, :first, :last, :name, :email, :phone, cast(:emails as jsonb), cast(:phones as jsonb), "
                "'[]'::jsonb, '[]'::jsonb, now(), now())"
            ),
            {
                'id': contact_id,
                'tenant': row['tenant_id'],
                'org': row['organization_id'],
                'account': row['id'],
                'first': first[:100] or None,
                'last': last[:100] or None,
                'name': (name or email or phone)[:320],
                'email': email or None,
                'phone': phone[:40] or None,
                'emails': json.dumps([{'value': email, 'primary': True}] if email else []),
                'phones': json.dumps([{'value': phone[:40], 'kind': 'office', 'primary': True}] if phone else []),
            },
        )
        bind.execute(
            sa.text('update taas_crm_accounts set primary_contact_id = :c where id = :a'),
            {'c': contact_id, 'a': row['id']},
        )


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
