"""Tenant-based blob storage: interfaces, types, errors, validation and settings (no cloud SDK).

Contract: `taas-specs/blob-storage-service/blob-service-spec.md`. Implementations: `blob_s3`, `blob_gcp`,
`blob_azure` (adapters) and `blob_service` (`create_blob_service`, memory adapter, tenant registries).
"""

from .blob_errors import (
    BlobConflictError,
    BlobError,
    BlobNotFoundError,
    BlobProviderError,
    BlobTenantNotFoundError,
    BlobValidationError,
)
from .blob_interfaces import (
    BlobAdapterT,
    BlobServiceT,
    TenantBlobStoreT,
    TenantBucketRegistryT,
    TenantId,
)
from .blob_settings import BlobSettings, get_blob_settings, normalize_provider
from .blob_types import (
    DEFAULT_CONTENT_TYPE,
    DEFAULT_LIST_LIMIT,
    DEFAULT_PRESIGN_EXPIRES,
    MAX_LIST_LIMIT,
    MAX_PRESIGN_EXPIRES,
    BlobBody,
    BlobInfo,
    BlobListOptions,
    BlobObject,
    BlobPage,
    BlobPresignMethod,
    BlobPresignOptions,
    BlobProvider,
    BlobPutOptions,
    TenantBucketRecord,
)
from .blob_validation import (
    BUCKET_NAME_PATTERN,
    MAX_KEY_BYTES,
    METADATA_KEY_PATTERN,
    attachment_disposition,
    body_to_bytes,
    normalize_metadata,
    resolve_presign_expires,
    strip_etag,
    validate_bucket_name,
    validate_key,
    validate_keys,
    validate_list_options,
    validate_metadata,
)

__all__ = [
    'BUCKET_NAME_PATTERN',
    'DEFAULT_CONTENT_TYPE',
    'DEFAULT_LIST_LIMIT',
    'DEFAULT_PRESIGN_EXPIRES',
    'MAX_KEY_BYTES',
    'MAX_LIST_LIMIT',
    'MAX_PRESIGN_EXPIRES',
    'METADATA_KEY_PATTERN',
    'BlobAdapterT',
    'BlobBody',
    'BlobConflictError',
    'BlobError',
    'BlobInfo',
    'BlobListOptions',
    'BlobNotFoundError',
    'BlobObject',
    'BlobPage',
    'BlobPresignMethod',
    'BlobPresignOptions',
    'BlobProvider',
    'BlobProviderError',
    'BlobPutOptions',
    'BlobServiceT',
    'BlobSettings',
    'BlobTenantNotFoundError',
    'BlobValidationError',
    'TenantBlobStoreT',
    'TenantBucketRecord',
    'TenantBucketRegistryT',
    'TenantId',
    'attachment_disposition',
    'body_to_bytes',
    'get_blob_settings',
    'normalize_metadata',
    'normalize_provider',
    'resolve_presign_expires',
    'strip_etag',
    'validate_bucket_name',
    'validate_key',
    'validate_keys',
    'validate_list_options',
    'validate_metadata',
]
