"""Business RBAC of the EWS apps: roles / permissions catalog (``data/ews-rbac.json``), its start-up
sync into ``taas_casbin_rule`` and the ``can`` decision — the same RBAC as the Node IAM (both catalogs,
shared vectors ``data/rbac-cases.json``). Specs: taas-specs/iam/specs/app-roles-spec.md, authorization-rbac-spec.md."""

from ._catalog import (
    EwsResources,
    PolicyRow,
    ProjectRoles,
    RbacCatalog,
    RbacRole,
    SiteRoles,
    catalog_owns_policy,
    builtin_catalogs,
    catalog_policies,
    effective_policies,
    evaluate,
    ews_catalog,
    iam_catalog,
    key_match,
    resource_domains,
    validate_catalog,
)
from ._store import (
    SyncResult,
    can,
    grant,
    granted_permissions,
    grants_in,
    revoke,
    revoke_domain,
    sync_catalog,
    user_domains,
)

__all__ = [
    'EwsResources',
    'PolicyRow',
    'ProjectRoles',
    'RbacCatalog',
    'RbacRole',
    'SiteRoles',
    'SyncResult',
    'can',
    'catalog_owns_policy',
    'builtin_catalogs',
    'catalog_policies',
    'effective_policies',
    'evaluate',
    'ews_catalog',
    'grant',
    'granted_permissions',
    'grants_in',
    'iam_catalog',
    'key_match',
    'resource_domains',
    'revoke',
    'revoke_domain',
    'sync_catalog',
    'user_domains',
    'validate_catalog',
]
