"""
Idempotency database model.

A single table — ``processed_events`` — records every (idempotency_key)
that has been committed to completion.  The primary uniqueness constraint
is the ``idempotency_key`` column, which is a composite of:

    "<handler_name>:<event_id>"

This scoping allows the same domain event to be fanout-processed by
multiple independent handlers without false-positive duplicate detection.

Index strategy
--------------
``idx_idempotency_key``        — unique, used for every INSERT/SELECT
``idx_idempotency_event_id``   — analytics / per-event lookup
``idx_idempotency_created_at`` — TTL cleanup sweep (DELETE old rows)
``idx_idempotency_tenant``     — tenant-scoped replay queries
"""
import datetime
from typing import Any, Optional

from advanced_alchemy.base import UUIDv7Base
from sqlalchemy import (
    JSON,
    TIMESTAMP,
    Index,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column, validates

from db.models.config import RESILIANT_TABLE_PREFIX


class ProcessedEventTable(UUIDv7Base):
    """
    Records events that have already been processed by a specific handler.

    One row per (handler_name, event_id) pair.  The ``idempotency_key``
    column stores the composite ``"<handler_name>:<event_id>"`` so lookups
    and inserts need only a single index scan.

    Columns
    -------
    idempotency_key
        Composite unique key — the only field tested during the
        hot-path INSERT … ON CONFLICT DO NOTHING.  Must be <= 512 chars.

    event_id
        Raw event ID from ``event.metadata.event_id``.

    event_type
        Raw event type string for analytics (e.g. ``"deposit.completed"``).

    handler_name
        Class name of the handler that successfully processed the event.

    saga_id
        Optional FK-style link to a saga row (stored as text, not a real FK,
        to avoid cross-schema coupling).

    correlation_id
        Propagated W3C correlation ID for distributed tracing.

    tenant_id
        Multi-tenancy support — allows per-tenant replay queries.

    extra_metadata
        Arbitrary JSON for future extensibility — do not rely on its schema.

    created_at
        Wall-clock time when the row was inserted (used for TTL cleanup).
    """

    __tablename__ = f'{RESILIANT_TABLE_PREFIX}processed_events'

    # ------------------------------------------------------------------
    # Primary key (surrogate — keeps the unique constraint narrow)
    # ------------------------------------------------------------------
    # id: Mapped[str] = mapped_column(
    #     Text,
    #     primary_key=True,
    #     comment='Surrogate primary key (generated by application)',
    # )

    # ------------------------------------------------------------------
    # Core idempotency fields
    # ------------------------------------------------------------------
    idempotency_key: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
        comment="Composite idempotency key: '<handler_name>:<event_id>'",
    )

    event_id: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment='Original event ID from event.metadata.event_id',
    )

    event_type: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        default='',
        comment="Event type for analytics (e.g. 'deposit.completed')",
    )

    handler_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment='Name of the handler that processed this event',
    )

    # ------------------------------------------------------------------
    # Optional traceability fields
    # ------------------------------------------------------------------
    saga_id: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment='Optional saga UUID for linking to saga_state rows',
    )

    correlation_id: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        comment='W3C correlation ID propagated from the original request',
    )

    extra_metadata: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSON,
        nullable=True,
        comment='Free-form JSON for future extensibility',
    )

    # ------------------------------------------------------------------
    # Timestamp (used for TTL cleanup — no updated_at needed)
    # ------------------------------------------------------------------
    created_at: Mapped[datetime.datetime] = mapped_column(
        TIMESTAMP(timezone=False),
        server_default=text('NOW()'),
        nullable=False,
        comment='Wall-clock time when the row was inserted',
    )

    @validates('created_at')
    def validate_tz_info(self, _: str, value: datetime.datetime) -> datetime.datetime:
        if value.tzinfo is None:
            value = value.replace(tzinfo=datetime.UTC)
        return value

    # ------------------------------------------------------------------
    # Indexes & constraints
    # ------------------------------------------------------------------
    __table_args__ = (
        # UNIQUE on the idempotency key — this is what makes ON CONFLICT work.
        UniqueConstraint('idempotency_key', name='uq_processed_events_key'),
        # Fast lookup by raw event_id (e.g. "show me all handlers that processed X").
        Index('idx_idempotency_event_id', 'event_id'),
        # TTL sweep: DELETE WHERE created_at < NOW() - INTERVAL '30 days'.
        Index('idx_idempotency_created_at', 'created_at'),
    )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def as_dict(self) -> dict[str, Any]:
        return {
            'id': self.id,
            'idempotency_key': self.idempotency_key,
            'event_id': self.event_id,
            'event_type': self.event_type,
            'handler_name': self.handler_name,
            'saga_id': self.saga_id,
            'correlation_id': self.correlation_id,
            'extra_metadata': self.extra_metadata,
            'created_at': (self.created_at.isoformat() if self.created_at else None),
        }

    def __repr__(self) -> str:
        return (
            f'<ProcessedEventTable key={self.idempotency_key!r} '
            f'handler={self.handler_name!r}>'
        )
